"""
WAF detection and fingerprinting
Identifies common WAFs to adjust testing strategy
"""

import httpx
from typing import Dict


class WAFDetector:
    # WAF fingerprints
    WAF_SIGNATURES = {
        'cloudflare': {
            'headers': ['cf-ray', 'cf-cache-status', '__cfduid'],
            'status_codes': [403, 1020],
            'body_patterns': ['cloudflare', 'attention required', 'ray id']
        },
        'akamai': {
            'headers': ['akamai-x-cache', 'akamai-ghost-ip'],
            'body_patterns': ['akamai', 'reference #']
        },
        'aws_waf': {
            'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
            'body_patterns': ['forbidden', 'request blocked']
        },
        'imperva': {
            'headers': ['x-iinfo'],
            'body_patterns': ['imperva', 'incapsula']
        },
        'sucuri': {
            'headers': ['x-sucuri-id'],
            'body_patterns': ['sucuri', 'access denied']
        },
        'wordfence': {
            'body_patterns': ['wordfence', 'generated by wordfence']
        }
    }
    
    def __init__(self):
        self.client = None
    
    async def detect(self, target: str) -> Dict:
        """Detect WAF on target"""
        result = {
            'detected': False,
            'type': None,
            'confidence': 0.0,
            'indicators': []
        }
        
        # Prepare test URL
        test_url = f"https://{target}/"
        if not target.startswith(('http://', 'https://')):
            test_url = f"https://{target}/"
        else:
            test_url = target
        
        try:
            async with httpx.AsyncClient(timeout=10, follow_redirects=True) as client:
                # Send benign request
                benign = await client.get(test_url)
                
                # Send malicious request to trigger WAF
                malicious = await client.get(
                    test_url,
                    params={'test': '<script>alert(1)</script>'}
                )
                
                # Analyze responses
                waf_type, confidence, indicators = self._analyze_response(
                    benign, malicious
                )
                
                if waf_type:
                    result['detected'] = True
                    result['type'] = waf_type
                    result['confidence'] = confidence
                    result['indicators'] = indicators
                
        except Exception as e:
            print(f"[!] WAF detection error: {e}")
        
        return result
    
    def _analyze_response(self, benign, malicious) -> tuple:
        """Analyze responses to identify WAF"""
        detected_wafs = {}
        
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            score = 0
            indicators = []
            
            # Check headers
            if 'headers' in signatures:
                for header in signatures['headers']:
                    if header.lower() in [h.lower() for h in malicious.headers]:
                        score += 30
                        indicators.append(f"Header: {header}")
            
            # Check status code
            if 'status_codes' in signatures:
                if malicious.status_code in signatures['status_codes']:
                    score += 25
                    indicators.append(f"Status: {malicious.status_code}")
            
            # Check body patterns
            if 'body_patterns' in signatures:
                body = malicious.text.lower()
                for pattern in signatures['body_patterns']:
                    if pattern in body:
                        score += 20
                        indicators.append(f"Body pattern: {pattern}")
            
            # Check if benign request succeeded but malicious failed
            if benign.status_code == 200 and malicious.status_code in [403, 406, 429]:
                score += 15
                indicators.append("Block on suspicious input")
            
            if score > 0:
                detected_wafs[waf_name] = (score, indicators)
        
        # Return highest scoring WAF
        if detected_wafs:
            best_match = max(detected_wafs.items(), key=lambda x: x[1][0])
            waf_type = best_match[0]
            score, indicators = best_match[1]
            confidence = min(score / 100, 1.0)
            return waf_type, confidence, indicators
        
        return None, 0.0, []